highlighter: false
markdown: rdiscount
rdiscount:
  extensions: [smart]
gems:
  - jekyll-sitemap
  - jekyll-paginate
permalink: pretty
paginate: 5
paginate_path: about/news/page:num/
url: http://campworkcoeman.org
collections:
    sahposts:
        output: true
collections_dir: scouting-at-home
